---
- name: install packages
  with_items: "{{ nginx_packages }}"
  pkgng:
    name: "{{ item.name }}"

- name: enable nginx service
  template:
    src: nginx.j2
    dest: /etc/rc.conf.d/nginx

- name: create conf.d directory
  file:
    path: /usr/local/etc/nginx/conf.d
    state: directory

- name: create certs directory
  file:
    path: /usr/local/etc/nginx/certs
    state: directory

- name: configure nginx
  template:
    src: nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf
